version: '3'

services:
    db:
        image: mysql:5.7
        volumes:
          - .data/:/var/lib/mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: demo
            MYSQL_DATABASE: patientsdb
            MYSQL_USER: patientsuser
            MYSQL_PASSWORD: patients
    phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - '7000:80'
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: demo