name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  pull_request_master:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: patientsdb
          MYSQL_USER: patientsuser
          MYSQL_PASSWORD: patients
        options: --health-cmd 'mysqladmin ping' --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm test